"""
citation_map.py — build review/citation_map.md: every source of the reference list
mapped to every place it is cited in the manuscript, in chronological order.

Purpose: manual verification after any edit to the manuscript. Line numbers shift with
every edit, so re-run this script instead of trusting an older copy of the table.

    python scripts/citation_map.py                 # paper/manuscript_en.md (default)
    python scripts/citation_map.py manuscript.md   # the Ukrainian version

Reports, besides the table:
  * sources that are never cited in the body (a reviewer's first check);
  * citation type per occurrence — parenthetical `(Author, year)` vs narrative
    `Author (year)`. APA 7: "&" is allowed only inside parentheses, narrative
    citations spell out "and" — the script flags violations.
Surname mentions in the metadata header (ORCID / "To cite" / author block) are listed
separately, so they are not miscounted as citations.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPER = ROOT / "paper"
SRC = PAPER / (sys.argv[1] if len(sys.argv) > 1 else "manuscript.md")
OUT = ROOT / "review" / "citation_map.md"

# 29.09.2026: список джерел читається з самого рукопису, а не з таблиці в коді.
# Захардкоджена таблиця на 9 позицій мовчки пропускала нові джерела, а пошук
# підрядком "[1" зараховував [13] і [17] до джерела 1. Тепер посилання [n] / [n, m]
# розбираються як числа (ЕлІТ: номер = порядок першої згадки).
CITE = re.compile(r"\[(\d+(?:\s*[,–-]\s*\d+)*)\]")


def cited_numbers(line: str) -> list[tuple[int, str]]:
    out = []
    for m in CITE.finditer(line):
        for part in re.split(r"\s*,\s*", m.group(1)):
            if re.search(r"[–-]", part):
                a, b = (int(x) for x in re.split(r"\s*[–-]\s*", part))
                out += [(n, m.group(0)) for n in range(a, b + 1)]
            else:
                out.append((int(part), m.group(0)))
    return out


def read_sources(text: str) -> list[tuple[int, str, str]]:
    """(номер, рік, коротка мітка) з нумерованого списку після заголовка літератури."""
    tail = re.split(r"^## (?:References|Література|Список літератури)", text, flags=re.M)[-1]
    out = []
    for m in re.finditer(r"^(\d+)\. (.+?)(?=^\d+\. |\Z)", tail, flags=re.M | re.S):
        entry = re.sub(r"\s+", " ", m.group(2))
        yr = re.search(r"\((\d{4})", entry)
        label = entry.split(". (")[0] if ". (" in entry else entry[:60]
        out.append((int(m.group(1)), yr.group(1) if yr else "?", label[:70]))
    return out


# header lines that merely contain a surname as metadata, not as a citation
META_PREFIXES = ("**ORCID:", "**To cite:", "**Yu. I. Kuzhii", "**Ю. І. Кужій", "Ю. І. Кужій —",
                 "Ю. М. Фургала —")


def body_lines(text: str) -> list[str]:
    """Manuscript text above the reference lists (citations only count in the body)."""
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.startswith(("## References", "## Література", "## Список літератури")):
            return lines[:i]
    return lines


def section_of(body: list[str], idx: int) -> str:
    for j in range(idx, -1, -1):
        if body[j].startswith(("## ", "### ")):
            return re.sub(r"^#+\s*", "", body[j]).strip()
    return "header block"


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    body = body_lines(text)
    SOURCES = read_sources(text)
    rows, meta_hits, uncited, apa_violations = [], [], [], []
    known = {n for n, _, _ in SOURCES}
    dangling = []

    for num, year, full in SOURCES:
        found = False
        for i, line in enumerate(body):
            if line.startswith("#"):
                continue
            hits = [form for n, form in cited_numbers(line) if n == num]
            if not hits:
                continue
            if line.startswith(META_PREFIXES):
                meta_hits.append((i + 1, line.split(":")[0].strip("*") or "author block"))
                continue
            found = True
            form = hits[0]
            pos = line.find(form)
            snippet = re.sub(r"\s+", " ", line[max(0, pos - 50):pos + len(form) + 30]).strip()
            rows.append((year, num, full, form, "numbered", section_of(body, i), i + 1, snippet))
        if not found:
            uncited.append((num, year, full))
    for i, line in enumerate(body):
        dangling += [(i + 1, form) for n, form in cited_numbers(line) if n not in known]

    rows.sort(key=lambda r: (r[0], r[1]))
    out = [
        f"# Citation map — {SRC.name}",
        "",
        f"All {len(SOURCES)} sources of the reference lists, chronologically, with every place each is cited.",
        f"Generated by `scripts/citation_map.py` — line numbers are valid only for the current state of {SRC.name}; re-run after edits.",
        "",
        "| Year | Ref # | Source | In-text citation | Type | Section | Line |",
        "|---|---|---|---|---|---|---|",
    ]
    out += [f"| {y} | {n} | {f} | `{form}` | {kind} | {sec} | {ln} |"
            for y, n, f, form, kind, sec, ln, _ in rows]

    out += ["", "## Context lines (for manual checking)", ""]
    out += [f"- **[{n}] {y}, line {ln}** — …{snip}…" for y, n, _, _, _, _, ln, snip in rows]

    out += ["", "## Mentions that are NOT citations (metadata)", "", "| Line | Block |", "|---|---|"]
    out += [f"| {ln} | {what} |" for ln, what in sorted(set(meta_hits))]

    out += ["", "## Checks", ""]
    out.append(f"- Sources never cited in the body: **{len(uncited) or 'none'}**"
               + ("".join(f"\n  - [{n}] {y} {f}" for n, y, f in uncited) if uncited else ""))
    out.append(f"- APA violations (narrative citation with `&` instead of `and`): **{len(apa_violations) or 'none'}**"
               + ("".join(f"\n  - line {ln}: `{f}`" for ln, f in apa_violations) if apa_violations else ""))
    out.append(f"- Citations to numbers absent from the list: **{len(dangling) or 'none'}**"
               + ("".join(f"\n  - line {ln}: `{f}`" for ln, f in dangling) if dangling else ""))
    first = []
    for line in body:
        if line.startswith("#") or line.startswith(META_PREFIXES):
            continue
        for n, _ in cited_numbers(line):
            if n not in first:
                first.append(n)
    ok = first == sorted(first)
    out.append(f"- Numbering follows order of first mention: **{'yes' if ok else 'NO'}**"
               + ("" if ok else f" (first-mention order: {first})"))

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"[saved] {OUT.relative_to(ROOT)}  ({len(rows)} citations, {len(SOURCES)} sources)")
    print(f"  uncited sources: {len(uncited)} | dangling: {len(dangling)} | "
          f"first-mention order: {'ok' if ok else 'BROKEN'}")


if __name__ == "__main__":
    main()
